path: matchs_gemini.csv

features:
 [
    'sum_assistant_a_tokens','sum_assistant_b_tokens',
    'sum_header_count_a','sum_header_count_b',
    'sum_list_count_a', 'sum_list_count_b',
    'sum_bold_count_a', 'sum_bold_count_b',

    'creative_writing_v0.1_creative_writing','creative_writing_v0.1_score',
    'criteria_v0.1_complexity', 'criteria_v0.1_creativity',
    'criteria_v0.1_domain_knowledge', 'criteria_v0.1_problem_solving', 'criteria_v0.1_real_world',
    'criteria_v0.1_specificity', 'criteria_v0.1_technical_accuracy',
    'if_v0.1_if', 'if_v0.1_score','math_v0.1_math',

    'is_code',

    'response_a_emoji_count', 'response_b_emoji_count',
    'response_a_table_count', 'response_b_table_count',
    'response_a_is_detailed','response_b_is_detailed',
    'response_a_word_count','response_b_word_count',
    'response_a_sentence_count','response_b_sentence_count',
    'response_a_avg_words_per_sentence', 'response_b_avg_words_per_sentence',
    'response_a_count_code_delimiters', 'response_b_count_code_delimiters', 
    'response_a_count_sentences_robust', 'response_b_count_sentences_robust',
    'response_a_count_punct_comprehensive','response_b_count_punct_comprehensive',
]

feature_pairs:
  - [sum_assistant_a_tokens, sum_assistant_b_tokens, sum_assistant_tokens]
  - [sum_header_count_a, sum_header_count_b, sum_header_count]
  - [sum_list_count_a, sum_list_count_b, sum_list_count]
  - [sum_bold_count_a, sum_bold_count_b, sum_bold_count]
  - [response_a_emoji_count, response_b_emoji_count, response_emoji_count]
  - [response_a_table_count, response_b_table_count, response_table_count]
  - [response_a_word_count, response_b_word_count, response_word_count]
  - [response_a_sentence_count, response_b_sentence_count, response_sentence_count]
  - [response_a_avg_words_per_sentence, response_b_avg_words_per_sentence, response_avg_words_per_sentence]
  - [response_a_count_code_delimiters, response_b_count_code_delimiters ,response_count_code_delimiters]
  - [response_a_count_punct_comprehensive, response_b_count_punct_comprehensive, response_count_punct_comprehensive]
  - [response_a_count_sentences_robust, response_b_count_sentences_robust, response_count_sentences_robust]


winner_map:
  1: Gemini Wins
  2: Other Model
  3: Tie
  4: Both Bad

